[package]
name = "kernel"
version = "0.1.0"
authors = ["dual-lab@yandex.com"]
edition = "2018"
repository = "https://github.com/dual-lab/jarvis"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

asm = { path = "../asm"}
